### ISSUE TITLE
Irregular rules checklist

### ISSUE THREAD

**Issue by neelsmith** [neelsmith/Kanones.jl#136]
- [ ] read tab-delimited to rule
- [ ] parse rule from fst
- [ ] convert to rule urn
- [ ] all citable trait methods
