### ISSUE TITLE
Irregular nouns checklist

### ISSUE THREAD

**Issue by neelsmith** [neelsmith/Kanones.jl#84]
- [x] read delimited into new IrregularNounForm object which contains complete data for a noun form. 
- [x] install irregular rules file into fst
- [x] install irregular stems file into fst
- [x] write acceptor/squasher for irregular form's fst
- [x] parse FST output from parsing into nounanalysis
- [x] generate irregular nouns from dataset.  generate will need to consider that a noun could be regular or irregular

**Comment by neelsmith** [comment]
done
