### ISSUE TITLE
Irregular verbs checklist

### ISSUE THREAD

**Issue by neelsmith** [neelsmith/Kanones.jl#85]
- [x] install irregular stems file into fst
- [x] read delimited into new IrregularVerbForm object which contains complete data for a verb form. 
- [x] parse FST output from parsing into verbanalysis
- [ ] generate irregular verbs from dataset.  generate will need to consider that a verb could be regular or irregular

**Comment by neelsmith** [comment]
closing
