### ISSUE TITLE
Irregular adjectives checklist

### ISSUE THREAD

**Issue by neelsmith** [neelsmith/Kanones.jl#86]
- [x] install irregular stems file into fst
- [x] read delimited into new IrregularIAdjectiveForm object which contains complete data for an infinitive form. 
- [x] parse FST output from parsing into adjective analysis
- [ ] generate irregular adjective from dataset.  generate will need to consider that an adjective could be regular or irregular

**Comment by neelsmith** [comment]
Omitting generate for now.  Taking that up in a separate milestone: closing this issue
