### ISSUE TITLE
Irregular infinitive checklist

### ISSUE THREAD

**Issue by neelsmith** [neelsmith/Kanones.jl#87]
- [x] install irregular stems file into fst
- [x] read delimited into new IrregularInfinitiveForm object which contains complete data for an infinitive form. 
- [x] parse FST output from parsing into infinitive analys
- [ ] generate irregular infinitve from dataset.  generate will need to consider that an infinitve could be regular or irregular

**Comment by neelsmith** [comment]
closing
